export const GET_USERS = 'GET_USERS'
export const USERS_REPOS ='USERS_REPOS'
export const LOADING_USERS = 'LOADING_USERS'
export const PAGE_NUMBER = 'PAGE_NUMBER'
export const USERS_ERROR = 'USERS_ERROR'
